# Generated by Django 5.1.4 on 2024-12-16 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
